os: linux
language: java
jdk: openjdk11

before_deploy:
    - mvn clean package

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: us-west-2
    upload_dir: apps/scheduling-software
#    local_dir: target
    cleanup: false
    glob: target/*-shaded.jar
    edge: true