language: java

jdk: openjdk11

script:
    - mvn clean package
    - mv target/SchedulingSoftware-shaded.jar SchedulingSoftware.jar

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    glob: SchedulingSoftware.jar
    upload-dir: $AWS_UPLOAD_DIR


