os: linux
language: java
jdk: openjdk11

before_deploy:
    - mvn clean package
    - mkdir app
    - cp ./docker-compose.yml ./app/docker-compose.yml
    - mv ./target/SchedulingSoftware.jar ./app/SchedulingSoftware.jar
    - zip -r SchedulingSoftware.zip ./app

deploy:
    on:
        branch: master
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: us-west-2
    acl: public_read
    upload_dir: apps/scheduling-software
    cleanup: false
    glob: SchedulingSoftware.zip
    edge: true