language: java

jdk: openjdk11

before_deploy:
    - mvn clean package
    - ls

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    glob: SchedulingSoftware-shaded.jar
    upload-dir: $AWS_UPLOAD_DIR