os: linux
language: java
jdk: openjdk11

before_deploy:
    - mvn clean package

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    upload_dir: $AWS_UPLOAD_DIR
    skip_cleanup: true
    glob: *-shaded.jar